config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :users, only: [:update, :show] do
    resources :appointments
    resources :dogs
  end

  get 'welcome/index'

  get 'welcome/service'

  get 'welcome/about'

  get 'welcome/contact'

  get 'users/:user_id/appointments/:id/thank_you' => 'appointments#thank_you', as: :thank_you
  get 'users/:user_id/booked_record' => 'appointments#booked_record', as: :booked_record

  root 'welcome#index'

end

app/models/dog.rb
class Dog < ActiveRecord::Base
  belongs_to :user
  has_many :appointments, through: :appointments_dogs
  has_many :appointments_dogs
  validates :birthday, presence: true
  validates :gender, presence: true
  validates :weight, presence: true
  validates :breed, presence: true
  validates :name, presence: true
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController

  def create
    @user = current_user
    @dog= Dog.new(params_dog)
    @dog.user = @user
  	if @dog.save
  		flash[:notice] = "Your dog information is saved"
  		redirect_to new_user_appointment_path(current_user)
  	else
  		flash[:error] ="Error saving the dog information"
  		render :new
  	end
  end	

  def index
  	@dogs = current_user.dogs.all
  end

  def show
  	@dog = Dog.find(params[:id])
  end

  def new
  	@dog = Dog.new
    @user = current_user
  end

  def edit
  	@dog = Dog.find(params[:id])
  end

  def update
  	@dog = Dog.find(params[:id])
	if @dog = @dog.update_attributes(params_dog)
  		flash[:notice] = "Your dog information is updated"
  		redirect_to new_user_dog_path(current_user, @dog)
  	else
  		redirect_to :back
  	end
  end

  def destroy
  	@dog = Dog.find(params[:id])
  	if @dog.destroy
  		redirect_to :back
  	else
  		flash[:error] ="Error deleting the dog information"
  		redirect_to :back
  	end


  end

  private

  def params_dog
  	params.require(:dog).permit(:name, :gender, :birthday, :weight, :breed, :mix)
  end
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/dogs/_dog.html.erb
<p><%= dog.name %><%= link_to "Edit", edit_user_dog_path(current_user, dog) %>|<%= link_to "Delete", user_dog_path(current_user, dog.id), method: :delete %></p>

app/views/dogs/_form.html.erb
<div class="row left-space">
    <div class="col-md-8">
    <%=form_for [user, dog]  do |f| %>
     <% if @dog.errors.any? %>
             <div class="alert alert-danger">
                <h4>There are <%= pluralize(dog.errors.count, "error") %>.</h4>
                <ul>
                    <% dog.errors.full_messages.each  do |msg| %>
                     <li><%= msg %></li>
                    <% end %>
                </ul>
             </div>
    <% end %>
        <%= form_group_tag(dog.errors[:name]) do %>
            <%= f.label :name %>
            <%= f.text_field :name %>
        <% end %>
        <div class="form-group">
            <%= f.label :gender %>
        
        <%= f.select :gender, [["Female", "f"], ["Male", "m"]] %> 
        </div>
        
        <div class="form-group">
            <%= f.label :birthday %>
            <%= f.date_select :birthday, start_year: 1990, end_year: Date.current.year %>
        </div>
            
        <%= form_group_tag(dog.errors[:weight]) do %>
            <%= f.label :weight %>(lbs)
            <%= f.text_field :weight, class: 'form-control' %>
        <% end %>
        <%= form_group_tag(dog.errors[:breed]) do %>
            <%= f.label :breed %>
            <%= f.text_field :breed, class: 'form-control' %>
        <% end %>   
        <div class="form-group">
            <%= f.label :mix %>
            <%= f.check_box :mix %>
        </div>  
        <div class="form-group">
            <%= f.submit "Save your dog information" %>
        </div>  
        <a href="javascript:history.back()">Go back to Appointment process</a>
     <% end %>
     </div>
     <% if current_user.dogs.any? %>
     <div class="col-md-4">
        <div class="form-group" %>
                <%= label :dog_id, "Please choose name of your dog to edit the information" %>
           <%= render partial: current_user.dogs %>

        </div>
    </div>
    <% end %>
</div>  

app/views/dogs/edit.html.erb
<%=render 'layouts/nav' %>
<%= render 'layouts/flash' %>
<div class="top">
<h1>Edit your dog's information.</h1>
<%= render partial: 'form', locals:{user: current_user, dog: @dog}  %>
</div>

app/views/dogs/index.html.erb
<h1>Dogs#index</h1>
<p>Find me in app/views/dogs/index.html.erb</p>
Commit 1
Commit 2
Commit 3
Commit 4

app/views/dogs/new.html.erb
<%=render 'layouts/nav' %>
<div class="left-space top">
<%= render 'layouts/flash' %>
<div class="top">
<h1>Plesae let us know about your dog.</h1>

<%= render partial: 'form', locals:{ user:@user, dog:@dog} %>
</div>
</div>