config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :users, only: [:update, :show] do
    resources :appointments
    resources :dogs
  end

  get 'welcome/index'

  get 'welcome/service'

  get 'welcome/about'

  get 'welcome/contact'

  get 'users/:user_id/appointments/:id/thank_you' => 'appointments#thank_you', as: :thank_you
  get 'users/:user_id/booked_record' => 'appointments#booked_record', as: :booked_record

  root 'welcome#index'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
belongs_to :user
#has_many :dogs, :through => :user
has_many :dogs, through: :appointments_dogs
has_many :appointments_dogs
accepts_nested_attributes_for :appointments_dogs
validates :app_date, presence: true
validates :check_in_time, presence: true
validates :telephone, presence: true
#
scope :visible_to, -> (user) { user.role == 'admin' ? all : where(user_id: user.id )}

# --removed validation because dog_id returns nil

after_create :send_confirmation_emails



# Normalizes the attribute itself before validation
#  validates_plausible_phone :telephone, presence: true
def self.unavailable_for?(appointment, dog_count)
  appts = Appointment.where(app_date: appointment.app_date)
  count = 0

  appts.each do |a|
    count += a.appointments_dogs.count
  end
  puts "*" * 20
 count += dog_count
  return count > 7

end

# retrieve the booked date
def self.booked_record
   booked_date = Array.new
   Appointment.all.each do  |d| 
     booked_date << d.app_date
  end
  booked_date.uniq.sort
end

# include phone info under new view
 def telephone=(num)
    num.gsub!(/\D/, '') if num.is_a?(String)
    super(num)
 end


# check the length of digits to 10 only
 def check_and_format_phone_number
    return if self.telephone.length == 11 && self.telephone.first == "1"
    if self.telephone.length != 10
      self.errors.add(:telephone, "can only be 10 digits")
    end
  end

private 
# once the appointment object is created sucessfully, the mail reminder is sent through Mailer
  def send_confirmation_emails
   user.dogs.each do |dog|
   	ConfirmationMailer.appointment_confirmation(dog.user, dog, self).deliver_now
   end
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  
  def create 
    #@user = current_user  
    # return if Appointment.fully_booked_for_today?
    #app_date = Date.new(params[:appointment][:app_date])

    dogs = params[:appointment][:dog_id]
    dogs.shift #dumps first blank id
    dog_count = dogs.count

   	@appointment = current_user.appointments.build(params_appo)


    if Appointment.unavailable_for?(@appointment, dog_count)
      flash[:error] = "No appt for that day"
      redirect_to :back and return
    end
     if dogs.any? && @appointment.save
      # create appointments_dog object for all dogs
      # paramsß will have dog ids
        dogs.each do |dog|
          @appointment.appointments_dogs.create(dog_id: dog.to_i)
        end
  

      #   current_user.dogs.each do |dog|
      #    @appointments_dogs = @appointment.appointments_dogs.create(dog_id: dog.id)
      #   end
      #if @appointments_dog.save

  		  flash[:notice] = "reservation confirmed"
  		  redirect_to thank_you_path(current_user, @appointment)
  	  elsif !dogs.any?
  		  flash[:error] = "You must select a dog to create an appointment."
  		  render :new
      else
        flash[:error] = "Something went wrong."
        render :new
  	  end
   end

  def index
    @appointments = Appointment.visible_to(current_user)

  end

  def show
    @appointment = Appointment.find(params[:id])
  end

  def thank_you
    @appointment = current_user.appointments.find(params[:id])
  end

  def new
    @appointment = Appointment.new
    @user = current_user
  end

  def edit
    @appointment = Appointment.find(params[:id])
    @user = User.find(params[:user_id])
    @appointment.user = @user
  end

  def update
    @appointment = Appointment.find(params[:id])
    @user = User.find(params[:user_id])
    @appointment.user = @user
    if @appointment.update_attributes(params_appo)
      flash[:notice] = "reservation confirmed"
      redirect_to thank_you_path(current_user, @appointment)    
    else
      flash[:error] = "Appointment is upated."
      redirect_to :back
    end
  end

  def destroy
    @appointment = Appointment.find(params[:id])
    if @appointment.destroy
      redirect_to :back, notice: "Appointment is deleted."
    else
      flash[:error] = "Appointment is deleted."
      redirect_to :back
    end
  end

  def booked_record
   puts "yea" #test
   puts params[:app_date] #test
   puts params[:user_id] #test
   @appointments = Appointment.where(app_date: params[:app_date]).order('check_in_time')
   @apps = Array.new
   @appointment_check_in_dates = @appointments.each do |app|
    @apps << app.check_in_time
   end
   puts @apps  #test
   respond_to do |format|
    format.js
    format.html
   end

  end

  private

  def params_appo
  	params.require(:appointment).permit(:app_date, :check_in_time, :telephone, :memo, :dog_id
      )
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper


#only allow to choose the certain times
def am_hour_select(field_name)
  select_tag(field_name,options_for_select([
  [Time.now, "01"], ["9:00", "02"],["9:00", "03"],["9:30", "04"]]))
end


end

app/views/appointments/_app.html.erb
<br>
<br>
<br>
<ul>
	<% @appointments.each do |app| %>
		<li>Check In Time:<%= app.check_in_time %>&nbsp&nbsp&nbsp
		Telephone: <%= app.telephone %>
		<% if app.user.first_name %>
		 <%= app.user.first_name %>
		<% end %>
		<% if app.user.last_name %>
		 <%= app.user.last_name %>
		<% end %>
		| <%= link_to "Edit", edit_user_appointment_path(app.user, app) %> | <%= link_to "Delete", user_appointment_path(app.user, app), method: :delete %>
		</li>
		<li>Dog Name(s):
		<% app.appointments_dogs.each do |app_dog| %>
		 <%= app_dog.dog.name %>.
		<% end %>
	     </li>
	     <br />
	<% end %>
</ul>

app/views/appointments/_appointment.html.erb
<%= content_tag :div, class: 'media', id: "appointment-#{appointment.id}" do %>
<ul>
	<li>Appointment Date:<%= appointment.app_date %></lh>
	<li>Check in time <%= appointment.check_in_time %> AM</li>
	<li>The name(s) of your dog: </li>
		<% appointment.appointments_dogs.each do |ap_dog| %>
			<% if ap_dog.dog %>
			 <%= ap_dog.dog.name %><br>
			<% end %>
			<% if !appointment.memo.empty? %>
    			<li>Any special memo: <%= appointment.memo %>(We will do the best to accommodate, but we are sorry that we can not guarantee.)</li>
    		<% end %>
    	<% end %>

</ul>
<% end %>

app/views/appointments/_appointments_dog_fields.html.erb
  <%= f.hidden_field :id %>  <%# <== ここと %>
  <%= f.select :dog_id, options_for_select([['---', nil]] + current_user.dogs.all.map{|m| [m.name, m.id]}, f.object.dog_id) %>

app/views/appointments/_form.html.erb
<%= render 'layouts/flash' %>
<div class="row">
	<div class="col-md-8">
		<%=form_for [user, appointment]  do |f| %>
			<% if appointment.errors.any? %>
			 <div class="alert alert-danger">
			 	<h4>There are <%= pluralize(appointment.errors.count, "error") %>.</h4>
			 	<ul>
			 		<% appointment.errors.full_messages.each  do |msg| %>
			 		 <li><%= msg %></li>
			 		<% end %>
			 	</ul>
			 </div>
			<% end %>
		<% if !appointment.app_date %>
			<h2><i> Please click the date on calendar to choose the appointment date.</i></h2>
			<br>
			<br>
		<% end %>
    </div>
</div>
<div class="row">
 <div class="col-md-8">
  <div id='calendar' class="center calendar-form"></div>
 </div>
 <div class="col-md-2 indicator-box-left">
  <div id="indicate-box-top">
   <div id="title-white"><h6>White: available dates</h6></div>
   <div id="white-box" class="indicate-box"></div>
   <div class="title"><h6>Pink:  booked dates</h6></div>
   <div id="pink-box" class="indicate-box"></div>
   <div class="title"><h6>Yellow: past dates</h6></div>
   <div id="yellow-box" class="indicate-box"></div>
  </div>
 </div>
 </div>  
 <div id="calendarModal" class="modal fade">
			<div class="modal-dialog">
   			 <div class="modal-content">
        		<div id="modalBody" class="modal-body"> </div>
        		<div class="modal-footer">
        			<button type="button" class="btn btn-primary" id="app_date_value">Yes</button>
            		<button type="button" class="btn btn-default" id ="app_date_nonselected" data-dismiss="modal">No</button>
        		</div>
    		</div>
		    </div>
	     </div>
	     <%= form_group_tag(appointment.errors[:app_date]) do %>
				<%= f.label :app_date, "Appointment Date" %>				
				<%= f.date_select :app_date, class:'form-control', id: 'app_date' %>
		 <% end %>

			<% if current_user.dogs.any? %>
				<%= f.label :dog_ids, "Please choose name of your dog. " %>
           		<%= f.collection_select :dog_id, current_user.dogs.all, :id, :name, {}, multiple: true, size: 3 %>
           		<p><i>If you do not choose one, you will be bringing one dog.</i></p>
           		<p><%= link_to "Add/Edit/Delete your dog information ", new_user_dog_path(current_user) %></p>
           	 <% else %>
           	  <p><%= link_to "Add your dog information or we understand you will be bringing one dog.", new_user_dog_path(current_user) %></p>
      
           	<% end %>
			<%= form_group_tag(appointment.errors[:check_in_time]) do %>
				<%= f.label :check_in_time %>
				<%= f.select :check_in_time, [["08:00 AM", "08:00"], ["08:30 AM", "08:30"], ["09:00 AM", "09:00"], ["09:30 AM", "09:30"]] %>
				(Please bring your dog(s) only those times.)
			<% end %>
			<%= form_group_tag(appointment.errors[:telephone]) do %>
				<%= f.label :telephone %>
				<% if current_user.phone_number && !appointment.telephone %>
				<%= f.text_field :telephone , :value => number_to_phone(current_user.phone_number), id: 'phone' %>
				<% else %>
				<%= f.text_field :telephone , :value => number_to_phone(appointment.telephone), id: 'phone'%>
				<% end %>
				

			<% end %>			
			<div class="form-group">
				<%= f.label :memo %>
				<%= f.text_area :memo%>
 			</div>	
 			<div class="form-group">
 				<%= f.submit "Next to confirm" %>
 			</div>	
		<% end %>
	</div>
</div>	
<script type="text/javascript">
 $(document).ready(function(){
 	 $('#appointment_app_date_1i').empty();
 	 $('#appointment_app_date_2i').empty();
 	 $('#appointment_app_date_3i').empty();
	
		var date = new Date();
		var d = date.getDate();
		var m = date.getMonth();
		var y = date.getFullYear();
		var month = new Array();
		month[0] = "January";
		month[1] = "February";
		month[2] = "March";
		month[3] = "April";
		month[4] = "May";
		month[5] = "June";
		month[6] = "July";
		month[7] = "August";
		month[8] = "September";
		month[9] = "October";
		month[10] = "November";
		month[11] = "December";
		

		
$('#calendar').fullCalendar({
	editable: true,
		dayRender : function(date, cell) {
		var today = new Date();
		var cellYear = date.format('YYYY');
		var cellMonth = date.format('MM');
		var cellDay = date.format('DD');
		     
		if (date < today) {
			cell.css("background-color", "yellow");
			cell.css("opacity", 0.5);
		}

	
		$('.fc-day').each(function(){
			var thisDate = $(this).attr('data-date');
			var td = $(this).closest('td');
			<% AppointmentsDog.list.each do |key, value| %>
			  if ('<%= key %>' == thisDate){
				td.addClass('background-pink');
			}
			<% end %>
		});
	},
	dayClick: function(date, jsEvent, view) {
		var today = new Date();
		var clicked_date = date;
		var sel_year = date.format('YYYY');
		var sel_month = date.format('MM');
		var sel_day = date.format('DD');
		console.log("you chose:" + sel_year + " " + sel_month + " " + sel_day);
       if (date > today && (!$(this).is('.background-pink')) &&(!$(this).is('.fc-sun'))&&(!$(this).is('.fc-mon'))&&(!$(this).is('.fc-tue'))){
       	//appointment.fully_booked_for_today?(date) 
        	// I could not specify the condition for  "&& ($(this).css('background-color')=="grey")"
         // change the day's background color just for fun
        // $(this).css('background-color', 'red');
         $('#modalBody').html("Would you like to book on" + date.format() + "?");
         $('#eventUrl').attr('href',event.url);
         $('#calendarModal').modal();       
    	 $('#app_date_value').click(function(){
    	 $('#calendarModal').modal('hide');
         $('#appointment_app_date_1i').empty();
         $('#appointment_app_date_1i').append("<option value ='" + sel_year + " selected = 'selected'>" + sel_year + "</option>");
         $('#appointment_app_date_2i').empty();
         $('#appointment_app_date_2i').append("<option value ='" + sel_month + " selected = 'selected'>" + month[sel_month - 1] + "</option>");
         $('#appointment_app_date_3i').empty();
         $('#appointment_app_date_3i').append("<option value ='" + sel_day + " selected = 'selected'>" + sel_day + "</option>");
   		 
		});
    	    	 
     }
    
    },

 	
	weekMode: 'liquid',  //fixed week count
// Boolean, default: true,  //resize the window
	url: '#',


   
	});
	
 })
</script>

app/views/appointments/booked_record.html.erb
<%=render 'layouts/nav' %>
<div class="row">
 <div class="col-md-8">
  <div id='calendar' class="center calendar-form"></div>
 </div>
 <div class="col-md-2 indicator-box-left">
  <div id="indicate-box-top">
   <div id="title-white"><h6>White: available dates</h6></div>
   <div id="white-box" class="indicate-box"></div>
   <div class="title"><h6>Pink:  booked dates</h6></div>
   <div id="pink-box" class="indicate-box"></div>
   <div class="title"><h6>Yellow: past dates</h6></div>
   <div id="yellow-box" class="indicate-box"></div>
   <div class="title"><h6>Grey: Store closed</h6></div>
   <div id="grey-box" class="indicate-box"></div>
  </div>
 </div>
 </div>
 <br>
 <br>
 <div id ='clicked_date' class="left-margin">
  Date: <%= select("appointment", "id", Appointment.booked_record, {include_blank: 'None'}) %>
 </div>
 
 <div id = 'loaded_zone'></div>

<script type="text/javascript">
 $(document).ready(function(){
 		var date = new Date();
		var d = date.getDate();
		var m = date.getMonth();
		var y = date.getFullYear();
		var month = new Array();
 $('#appointment_id').change(function() {
	//ajax request to appointment#booked_record
 $.ajax({ type: "GET",   
           url: "booked_record", 
           data: { app_date: $('#appointment_id').val() }

  });

 });
				
 $('#calendar').fullCalendar({
	editable: true,
		dayRender : function(date, cell) {
		var today = new Date();
		var cellYear = date.format('YYYY');
		var cellMonth = date.format('MM');
		var cellDay = date.format('DD');
		if (date < today) {
			cell.css("background-color", "yellow");
			cell.css("opacity", 0.5);
		}

	
		$('.fc-day').each(function(){
			var thisDate = $(this).attr('data-date');
			var td = $(this).closest('td');
			<% AppointmentsDog.list.each do |key, value| %>
			  if ('<%= key %>' == thisDate){
				td.addClass('background-pink');
			}
			<% end %>
		});
	},
	dayClick: function(date, jsEvent, view) {
		var today = new Date();
		var clicked_day= date.format('MM-DD-YYYY');
		console.log("you chose:" + clicked_day);
       if ((!$(this).is('.fc-sun'))&&(!$(this).is('.fc-mon'))&&(!$(this).is('.fc-tue'))){
       	 $('#clicked_date').empty();
         $('#clicked_date').append("Appointment List on Date: " + clicked_day);
           $('#clicked_date').append(
        
         );
  	 
     }
    
    },
   weekMode: 'liquid',  //fixed week count
   Boolean, default: true,  //resize the window
   url: '#',
   });
 })
</script>

app/views/appointments/booked_record.js.erb
$('#appointment_id').after("<%=j render 'app' %>");

app/views/appointments/edit.html.erb
<%= render 'layouts/nav' %>
<div class="left-space">
  <h1>Change the reservation?</h1>
  <%= render partial: 'form', locals: { user: current_user, appointment: @appointment} %>
</div>

app/views/appointments/index.html.erb
<%=render 'layouts/nav' %>

<%= render 'layouts/flash' %>
<div class="left-space">
<h1>Appointment </h1>
	<h2>Upcoming Appointment</h2>
	 <% @appointments.each do |apt| %>
	  <% if apt.app_date >= DateTime.now %>
	 	<p>On <%= apt.app_date %> at <%= apt.check_in_time %> for <% apt.dogs.each do |dog| %>  
	 		<%= dog.name %>
	 		<% end %>
	 		<%= link_to "Edit", edit_user_appointment_path(current_user, apt) %> | <%= link_to "Delete", user_appointment_path(current_user, apt), method: :delete %></p>
	  <% end %>
	 <% end %>
	 <h2>Completed Appointment</h2>
	  <% @appointments.each do |apt| %>
	  	<% if apt.app_date < DateTime.now %>
	 		<p>On <%= apt.app_date %> at <%= apt.check_in_time %> for <% apt.dogs.each do |dog| %>
	 			<%= dog.name %>  
	 			<% end %>
	  	<% end %>
	  <% end %>

</div>

app/views/appointments/new.html.erb
<%=render 'layouts/nav' %>
<div class="left-space">
  <h1>Start to make an appointment</h1>
  <%= render partial: 'form', locals: { user: current_user, appointment: @appointment} %>
</div>

app/views/appointments/show.html.erb
<h1>Appointments#show</h1>
<p>Find me in app/views/appointments/show.html.erb</p>

app/views/appointments/thank_you.html.erb
<%=render 'layouts/nav' %>
<div class="top">
<h1> Thank you for completing the reservation  <%= (current_user.first_name || current_user.last_name) if (current_user.first_name || current_user.last_name) || current_user.email %>.</h1>

<p>The confirmation letter is sent to your email address: <%= current_user.email %>.</p>

<p>We will call you at <%= number_to_phone(@appointment.telephone) %> to confirm the reservation previous day from the reservation date: <%= @appointment.app_date %><p>

Here is the summary of your reservation.
<%= render @appointment %>

<p>We look forward to seeing you and your loved one soon!</p>

<p>Thank you for choosing Fuji Pet Salon.</p>
</div>
<%= link_to "Log Out", destroy_user_session_path, method: :delete , class: "btn btn-lg btn-success" %>