config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :users, only: [:update, :show] do
    resources :appointments
    resources :dogs
  end

  get 'welcome/index'

  get 'welcome/service'

  get 'welcome/about'

  get 'welcome/contact'

  get 'users/:user_id/appointments/:id/thank_you' => 'appointments#thank_you', as: :thank_you
  get 'users/:user_id/booked_record' => 'appointments#booked_record', as: :booked_record

  root 'welcome#index'

end

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <%= flash[:notice] %>
    </div>
<% elsif flash[:error] %>
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
    </div>
<% elsif flash[:alert] %>
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
    </div>
<% end %>

app/views/layouts/_index_nav.html.erb
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top affix-top">
   <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="true">
         <span class="sr-only">Toggle navigation</span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
        </button>
       <a class="navbar-brand page-scroll" href="#page-top">Fuji Pet Salon</a>
      </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
       <div class="navbar-collapse collapse navbar-right" id="bs-example-navbar-collapse-1" aria-expanded="true" >
         <ul class="nav navbar-nav navbar-right　dropdown-menu" >
          <li class="">
           <a class="page-scroll" href="#about">About</a>
          </li>
           <li class="">
             <a class="page-scroll" href="#services">Services</a>
           </li>
           <li class="">
           <a class="page-scroll" href="#portfolio">Portfolio</a>
           </li>
           <li class="">
            <a class="page-scroll" href="#contact">Contact</a>
           </li>
            <% if current_user %>
              <li class=""><%= link_to current_user.email, edit_user_registration_path %>
               <li class=""><%= link_to "Log out", destroy_user_session_path, ethod: :delete , class: "page-scroll" %></li>
              <% end %>
         </ul>
         </div>
          <!-- /.navbar-collapse -->
       </div>
       <!-- /.container-fluid -->
</nav>

app/views/layouts/_nav.html.erb
 <nav id="mainNav" class="navbar navbar-reverse affix-top navbar-background">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="true">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand page-scroll" href="/">Fuji Pet Salon</a>
     </div>
           <!-- Collect the nav links, forms, and other content for toggling -->
     <div class="navbar-collapse collapse navbar-right" id="bs-example-navbar-collapse-1" aria-expanded="true">
       <ul class="nav navbar-nav navbar-right　dropdown-menu">
        <% if current_user %>
         <% if policy(current_user).role? %>
           <li class=""><%= link_to "Future Booked records", booked_record_path(current_user) %>
          <% end %>  
           <li class=""><%= link_to "New reservation", new_user_appointment_path(current_user) %></li>
           <li class=""><%= link_to "Your reservation", user_appointments_path(current_user) %></li>
           <li class=""><%= link_to "Your profile", edit_user_registration_path %></li>
           <li class=""><%= link_to "Log out", destroy_user_session_path, method: :delete , class: "page-scroll" %></li>
        <% end %>
       </ul>
     </div>
            <!-- /.navbar-collapse -->
   </div>
        <!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta name="description" content="">
   <meta name="author" content="">
   <!-- saved from url=(0057)http://ironsummitmedia.github.io/startbootstrap-creative/ -->
   <meta http-equiv="Content-Type" content="text/html">

   <title>Fuji Pet</title>   
   <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
   <%= javascript_include_tag 'jquery.fittext' %>
   <%= javascript_include_tag 'jquery.easing.min', 'wow.min', 'creative', 'cbpAnimatedHeader', 'classie', 'jquery.maskedinput', 'underscore' %>   

   <!-- Custom Fonts -->
   <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
   <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'creative', 'font-awesome','font-awesome.min', 'animate.min', 'css' %>
  
 	
  <%= csrf_meta_tags %>
    
</head>
<body id="page-top" cz-shortcut-listen="true" data-spy="scroll">
  
<%= yield %>
<h5 class="text-center">© Copyright Fuji Pet Salon. 2015.  All Rights Reserved</h5>
</body>
</html>